//Recipes
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_START = 'GET_RECIPES_START';
export const GET_RECIPES_FAIL = 'GET_RECIPES_FAIL';

//User
export const ADD_FAV = 'ADD_FAV';
export const DELETE_FAV = 'DELETE_FAV';

export const GET_FAV_START = 'FAV_LOADING';
export const GET_FAV_SUCCESS = 'GET_FAV';
export const GET_FAV_FAIL = 'FAV_STOP_LOADING';

//Auth
export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAIL = 'USER_LOADING_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const SET_ERROR = 'SET_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
